### ISSUE TITLE
The gender not getting store during the sign up

### ISSUE THREAD

**Issue by ArunTeltia** [coding-blocks/oneauth#1025]
when i try to make a new id on online.codingblocks.com and fill all the data including gender and try to sign up the gender is not getting stored in the database

during signup
![error](https://user-images.githubusercontent.com/43555219/84285393-0d325f00-ab5b-11ea-80d2-f546a17e9167.png)

after signup
![error1](https://user-images.githubusercontent.com/43555219/84285474-25a27980-ab5b-11ea-87ae-4700d1f351fd.png)
Please check this issue @abhishek97 
I want to work on this issue

**Comment by abhishek97** [comment]
@ArunTeltia you digged into it? did you found the bug?

**Comment by ArunTeltia** [comment]
@abhishek97 no bhaiya i dont start working on it right now if you give it a okay sign i will start working on it

**Comment by championswimmer** [comment]
Yes you can start @ArunTeltia

**Comment by ArunTeltia** [comment]
Okay bhaiya starting write now
