### ISSUE TITLE
Menu Item Not Visible 

### ISSUE THREAD

**Issue by roubalsehgal** [coding-blocks/oneauth#1035]
On the Page **https://account.codingblocks.com/users/me**
One of the items from 
- My Profile
- My Addresses
- My Organizations
- My Apps

**MY APPS** item (in desktop view) is not visible properly.
Screenshots of the Issue is attached below⤵

**DESKTOP VIEW** ⤵

![Screenshot (140)](https://user-images.githubusercontent.com/44202409/83130750-6aaac280-a0fc-11ea-8bd1-38d0d3f17e43.png)

**MOBILE VIEW** ⤵

![Screenshot (142)](https://user-images.githubusercontent.com/44202409/83130770-7302fd80-a0fc-11ea-923f-fb0941e631d5.png)

**Comment by championswimmer** [comment]
Good catch, you can try to solve it under boss

**Comment by roubalsehgal** [comment]
Yes! Working on it. Will make Pull Request by tomorrow.

**Comment by deprov447** [comment]
@championswimmer Is someone working on this? If not, I'd like to fix this.

**Comment by roubalsehgal** [comment]
@deprov447 
I'm working on this!

**Comment by championswimmer** [comment]
Both of you can submit a PR for this. We will take whichever is done better.
