### ISSUE TITLE
allow changing emails before they are verified

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/oneauth#120]

**Comment by knrt10** [comment]
I would like to work on this issue.

**Comment by championswimmer** [comment]
Please go ahead and do so. We are not **assigning** issues under BOSS, as then sometimes we forget to un-assign when the person doesn't complete in given time, and no one else gets to do it. If you feel like attempting any issue, just comment on the issue and start working on it. The first PR, which best solves the problem will be accepted.
