### ISSUE TITLE
Overflowing text in Oauth links

### ISSUE THREAD

**Issue by himanshuc3** [coding-blocks/oneauth#127]
![screen shot 2018-05-15 at 1 41 14 pm](https://user-images.githubusercontent.com/19166045/40044678-bd972828-5845-11e8-933c-2a31f71f1f17.png)
Filing a bug report: #14 
@championswimmer Please take a look. 
Would I get the bounty?

**Comment by bhavyaagg** [comment]
@championswimmer Please close this
