### ISSUE TITLE
Updating branch name leads to server error

### ISSUE THREAD

**Issue by ankurg22** [coding-blocks/oneauth#132]
Steps-
1. Login to account.codingblocks.com/users/me
2. Edit profile
3. Select any branch
4. Submit.
It will throw an error called "Error in server"
![screenshot from 2018-05-15 20-38-54](https://user-images.githubusercontent.com/16597330/40071630-f7f04894-588e-11e8-9bbd-1300888a5ffb.png)

#14

**Comment by championswimmer** [comment]
dupe https://github.com/coding-blocks/oneauth/issues/134

**Comment by ankurg22** [comment]
I think the one which later re-phrased the issue is duplicate. :+1:

**Comment by championswimmer** [comment]
It correctly mentions that college name also causes the error. Never mind. Point is to now solve the error :D
