### ISSUE TITLE
show 'full name' in connected to Facebook message

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/oneauth#143]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/1327050/40238899-2672b2ac-5ad2-11e8-9cc2-ca58691c4d38.png">

Here show full name (as fetched from FB, should be in userfacebook table) instead of the id
Link should still remain id.

**Comment by bhavyaagg** [comment]
@championswimmer Please close this issue.

**Comment by himanshuc3** [comment]
@championswimmer Also I made a claim for the bounty on this issue. Please approve that.

**Comment by championswimmer** [comment]
If you want claims to processed faster, also mention link to claim

**Comment by himanshuc3** [comment]
I think i did. I apologize if I forgot.

**Comment by championswimmer** [comment]
No i mean link this this 

https://boss.codingblocks.com/claims/49 

mention that here
