### ISSUE TITLE
change message to "verify email first"

### ISSUE THREAD

**Issue by till-tomorrow** [coding-blocks/oneauth#167]
![verifyemail](https://user-images.githubusercontent.com/21954525/40608864-8ca953cc-628a-11e8-885a-298f856925e0.JPG)

change message to "verify email first!" instead of "error in server".
in reference to #14

**Comment by championswimmer** [comment]
When is this error faced ?

**Comment by championswimmer** [comment]
I don't think this error is due to verification problem. Must be some other thing

**Comment by VibhorCodecianGupta** [comment]
Please close this issue @championswimmer if its resolved?
