### ISSUE TITLE
Social sign-in buttons are not looking good in web view.

### ISSUE THREAD

**Issue by piyush0** [coding-blocks/oneauth#17]
![screen shot 2017-04-22 at 3 31 15 pm](https://cloud.githubusercontent.com/assets/20954567/25303468/37c18e1a-2771-11e7-90c8-cef396286660.png)

Make the buttons more responsive.

**Comment by realslimshanky** [comment]
Hi, I'm looking into this issue.

**Comment by championswimmer** [comment]
@realslimshanky it is already being worked upon at #32

**Comment by realslimshanky** [comment]
Okay, thanks for the heads up. Will look into some other issue.
