### ISSUE TITLE
refactor the strategy promises into async/await code

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/oneauth#181]
The `src/passport/strategies/user/*` files have deeply nested Promises.

Turning them into asyns/await will be wonderful!

**Comment by architkshk** [comment]
On it.

**Comment by VibhorCodecianGupta** [comment]
Done, #184

**Comment by Dhroov7** [comment]
@championswimmer Done ! PR #198

**Comment by ananay** [comment]
Done here: https://github.com/coding-blocks/oneauth/pull/204
Fixed indentation and code quality issues as well

**Comment by ananay** [comment]
@championswimmer Please close this
