### ISSUE TITLE
refactor code to es6 arrow functions

### ISSUE THREAD

**Issue by Prawesome** [coding-blocks/oneauth#182]
Some of the functions are written in the traditional way, while some are ES6 arrow functions. Changing all functions to arrow functions where they don't cause binding problems could help increase readability

**Comment by championswimmer** [comment]
> where they don't cause binding problems

Keep in mind sometimes we need dynamic this instead of lexical this. Arrow functions aren't always _better_ than normal functions

**Comment by Prawesome** [comment]
Yes, which is why I mentioned that only those functions which don't need the dynamic **this** be refactored

**Comment by championswimmer** [comment]
sounds good. proceed with this if you want to

**Comment by architkshk** [comment]
@championswimmer Done!! #208 Please review.

**Comment by Dhroov7** [comment]
@championswimmer Done! PR #209

**Comment by Prawesome** [comment]
Done, async functions also refactored! @championswimmer PR #210

**Comment by championswimmer** [comment]
closing this. i cannot see any value in this, and needlessly generates a lot of churn in the code
