### ISSUE TITLE
No option for gender

### ISSUE THREAD

**Issue by firefinchdev** [coding-blocks/oneauth#193]
There is no mechanism for storing gender details in the profile.
I would like to work on this issue.

**Comment by Dhroov7** [comment]
@championswimmer Done!! PR #201

**Comment by architkshk** [comment]
@championswimmer Done in #202

**Comment by VibhorCodecianGupta** [comment]
Done @championswimmer in #301

**Comment by VibhorCodecianGupta** [comment]
@championswimmer any feedbacks on #301 😅 ?
