### ISSUE TITLE
Column `deletedAt` not found

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [coding-blocks/oneauth#200]
This is most definitely related to the `paranoid` option in the `users` model. I have tried adding a migration script and modifying the database to add the `deletedAt` column, with no success. This error keeps popping.
Tried googling the error too, could not find a potent solution to this. 

![screen shot 2018-06-08 at 6 19 22 pm](https://user-images.githubusercontent.com/29275810/41162976-0d9f9e1e-6b55-11e8-8184-cb6250970dc4.png)

Login of already registered users who were deleted by the `paranoid` option, or registering new users, neither works.
Relevant links (most relevant):
https://stackoverflow.com/questions/24611778/how-to-include-the-deleted-elements-when-querying-a-paranoid-table-on-sequeliz
https://github.com/sequelize/sequelize/issues/809

@championswimmer @Dhroov7

**Comment by VibhorCodecianGupta** [comment]
I also tried dropping the table and creating a fresh one like so:

![screen shot 2018-06-08 at 8 04 24 pm](https://user-images.githubusercontent.com/29275810/41163912-9123747a-6b57-11e8-911a-d4a157b21b8c.png)

I figured it would be a problem with existing users on the database because when users are queried with the paranoid option, the deletedAt column would be null for old users. But dropping the table also doesn't work, new user registration gives authentication error.

**Comment by championswimmer** [comment]
use `db.sync({alter: true})` to make any model changes update the table.
