### ISSUE TITLE
Create new designs in motley

### ISSUE THREAD

**Issue by witty123** [coding-blocks/oneauth#211]
https://github.com/coding-blocks/motley 

- [ ] My Profile card + edit profile card - 1000 BOUNTY
- [ ] Address card + edit address card + add address card - 1000 BOUNTY
- [ ] Secondary Nav - 500 BOUNTY
- [ ] Apps card - 500 BOUNTY
- [ ] Client cards + edit client card - 1000 BOUNTY

Redesign of account.codingblocks.com as per motley guidelines. I'll share the designs with the contributor who wants to work on this issue.

**Comment by lazy-god** [comment]
I will be working on this issue

**Comment by VibhorCodecianGupta** [comment]
Would like to work on this!

**Comment by architkshk** [comment]
@witty123 I want to work on this issue

**Comment by kapillamba4** [comment]
I would like to work on this, my email is kapillamba4@gmail.com

**Comment by venomousboxer** [comment]
would also like to work on the issue my mail is y.mohit03031999@gmail.com

**Comment by architkshk** [comment]
@witty123 Please share the designs.

**Comment by witty123** [comment]
Guys I'm waiting for the first PR to be closed. This issue will need multiple PRs.
https://github.com/coding-blocks/motley/pull/180
After this I'll be sharing the designs so that everyone can take help from this PR and contribute accordingly. Thanks for the patience.

**Comment by Kapil706** [comment]
I want to work on this email is : kapilchaudhary706@gmail.com

**Comment by championswimmer** [comment]
This is done now

@lazy-god awarding 3000 bounties, as you got a lot of help from the CB team, so wouldn't be fair to get all 4000 points
