### ISSUE TITLE
Create a sample front+backend app showing explicit-flow in action

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/oneauth#23]

**Comment by abhishek97** [comment]
I've created a sample app here : https://github.com/abhishek97/oneauth-example
Please check.

**Comment by rahulyadav170923** [comment]
so the app is available at -: https://demoappcb.herokuapp.com/
I did not put much front end. You have a logout url in the user data itself.

**Comment by championswimmer** [comment]
@abhishek97 Your demo is not working

**Comment by championswimmer** [comment]
@rahulyadav170923 
Could you show the user data in a formatted page, instead of raw json. Looks more beautiful that way

**Comment by abhishek97** [comment]
@championswimmer  sorry, here : https://oneauth-example.herokuapp.com/

**Comment by championswimmer** [comment]
@abhishek97 since it is a sample app, i suggest you keep actual values of callbackUrl etc in config, so it makes sense, and can be tested from the word go

**Comment by championswimmer** [comment]
@abhishek97 Also can we have two examples - one using requests directly, and another using passport oauth2. 
make two directories, and `npm run request` and `npm run passport`

**Comment by abhishek97** [comment]
@championswimmer  please check now. you can  run with single command. `config.json` is ready to run out of the box

**Comment by rahulyadav170923** [comment]
@championswimmer made the changes .  https://demoappcb.herokuapp.com/

**Comment by championswimmer** [comment]
Taking @abhishek97's one. It has both request and passport editions

**Comment by championswimmer** [comment]
@abhishek97 please claim your bounty for the same
