### ISSUE TITLE
[QUEST] abstract out a 'controller' layer in between routes and models

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/oneauth#243]
Right now routes are dealing directly with models.
As a lot of redundancy in page routes and api routes increase, we need a controller layer. (For eg `/api/users/me` and `/users/me` )

What will controllers do ? 
Controllers will supply functions like the following
(written in Typescript to show return types
```ts

function getUsers(): Promise<User[]>
function getUserById(userId: number): Promise<User>
```

Which means we can have routes simply do this - 

```js
// API routes
app.get('/api/users/:id', async (req, res) => {

	const user = await getUserById(req.params.id)
	res.json(user)

})

// Page routes
app.get('/users/:id', async (req, res) => {
	const user = await getUserById(req.params.id)
	res.render('user/id', user)
})
```

We need to start abstracting the most used models into controllers first 

- [ ] users
  - [ ] demographics (including addresses)
- [ ] clients
- [ ] authtokens

**Comment by Dhroov7** [comment]
@championswimmer Done PR #249

**Comment by VibhorCodecianGupta** [comment]
@championswimmer  #246 will be complete now, and everything squashed into a single commit.

**Comment by championswimmer** [comment]
Everyone has to fix some conflicts I guess. Merged some address and demograhic related PRs that will conflict will all of your PRs.

**Comment by championswimmer** [comment]
So I was taking a final look at the PRs. 

First things - 

-1 to @VibhorCodecianGupta because at least 8 files are changed simply because of whitespace issues. 
This issue should need changes to around 15 files only where the models are accessed.

**Comment by championswimmer** [comment]
Ok I have merged @architkshk's PR, because in my opinion it was the best.
But that said - 

1. None of the current PRs were **wrong** per se, they all achieved what the issue was about. So no one will get 0 bounty

2. Not even @architkshk did it purely on his own. Everyone had to be nitpicked and code-reviewed multiple times. So no one will get 4000 bounty either. 


These are the bounties I have in mind for all 4 of you. Please claim accordingly on BOSS. 

3000 @architkshk 
2000 @Dhroov7 
1000 @VibhorCodecianGupta 
1000 @Rishabh570

**Comment by VibhorCodecianGupta** [comment]
@championswimmer thanks for the bounty!
Just for the sake of taking something away from this, I mean to ask - what was lacking and how can it be improved? Did I underdo/overdo it, was the code not clean/elegant enough etc.

Again, I just wish to know what was the scope of improvement in my respective PR. I am not requesting for more bounty, I have already made the claim, just looking for feedback. Thanks again!

**Comment by architkshk** [comment]
@championswimmer Thank you for the bounty!

**Comment by championswimmer** [comment]
@VibhorCodecianGupta 

The first thing ofcourse is the stray files committed. When writing code, it is easy to feel "even after  doing all right, you can't look past some whitespaces?" but if you see code reviews of bigger projects like AOSP, Chromium, Linux, KDE etc, you 'll see many good PRs are not even reviewed before whitespace issues are resolved. 

There were pluralization issues (eg `getDemographic"s"` for a function that returns only one demographic etc)

Ideally in update functions, you take the identifier first, the update options second. 

Prefer to stick to create/update/get/find/delete naming convention. Do not use `generateGrantCode` when `createGrantCode` is sufficiently good naming alternative. Whether the creation internally autoincrements, or random-generates is an implementation detail that the controller need not expose in the function name. 

`findAllTokens` - what kind of tokens? should be `findAuthTokens` 

`getUserOfTrustedClient` can probably use a single function `getUser` with a optional boolean `trustedClient` in second var.

**Comment by VibhorCodecianGupta** [comment]
Awesome, will keep this in mind. Thanks a lot @championswimmer !
