### ISSUE TITLE
reduce paddings and bloat in login page

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/oneauth#255]
the social login buttons must be visible in first fold even in small laptop screens

<img width="1672" alt="image" src="https://user-images.githubusercontent.com/1327050/42383373-a6eb3aaa-8154-11e8-83ff-5a13c358568e.png">

**NOTE** the changes must be done on https://github.com/coding-blocks/motley not here

**Comment by championswimmer** [comment]
For eg, looks much better like this 

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/1327050/42383603-50664c3c-8155-11e8-8cc2-9fd8de3e5919.png">

**Comment by VibhorCodecianGupta** [comment]
Need some help setting this up. Tried a bunch of things, no success

`git submodule init` shows `fatal: No url found for submodule path 'motley' in .gitmodules`

After this I deleted the submodule from `.git/config` and from `.git/modules`, and ran the command `git rm --cached motley` to clear the entry from `.git/index`. Then i retired the process by first doing:

`git submodule add <url> <name>`
where url is git submodule add https://github.com/coding-blocks/motley.git submodules/motley
and name is submodules/motley

and repeated the process in the readme. Again, no success.

@championswimmer @architkshk

**Comment by championswimmer** [comment]
@VibhorCodecianGupta don't use it with a submodule

Clone motley separately, run `npm run dist` in motley and use that generated CSS

**Comment by VibhorCodecianGupta** [comment]
@championswimmer you mean the generated `app.css` could be pasted in static CSS of oneauth, and then modified? It's not working that way either

**Comment by championswimmer** [comment]
That's exactly how it is runnin in production

**Comment by VibhorCodecianGupta** [comment]
Done, #224 @championswimmer

**Comment by championswimmer** [comment]
Rather, done via https://github.com/coding-blocks/motley/pull/219

**Comment by VibhorCodecianGupta** [comment]
@championswimmer [this PR](https://github.com/coding-blocks/motley/pull/224) also reduces the grey backdrop from the `forgot?` buttons (just like the sample design you posted above) and reduces the padding of `enter username` and `enter password` to prevent them wrapping when screen size and hence the input field size decreases. Just saying, these changes could be a good addition for oneauth.
