### ISSUE TITLE
add paddings around top right photo

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/oneauth#256]
looks odd stuck to the edges of the corner.

add some padding to make it look better

<img width="601" alt="image" src="https://user-images.githubusercontent.com/1327050/42384025-8cf5497c-8156-11e8-95a5-7faa4864ea4c.png">

**NOTE: Changes must be done on https://github.com/coding-blocks/motley**

**Comment by VibhorCodecianGupta** [comment]
Done on this [PR ](https://github.com/coding-blocks/motley/pull/222)
