### ISSUE TITLE
Address page issue

### ISSUE THREAD

**Issue by witty123** [coding-blocks/oneauth#265]
- [x] Label should come on top instead of at the bottom, placeholder text should be "Home, Office etc", Label should be a non mandatory field.
<img width="919" alt="screen shot 2018-07-15 at 11 04 57 am" src="https://user-images.githubusercontent.com/7976098/42730881-3741c97c-881f-11e8-883d-bc241afc180e.png">

- [ ] ~~"Edit address page" has incomplete binding, label and firstname is repeated at top, label and state data is inconsistent~~

- [x] Add whatsapp number as a separate field in the address table, can be same as contact number

**Comment by VibhorCodecianGupta** [comment]
@witty123 the issue of label and firstname being repeated has been resolved in  [1a1e0f8](https://github.com/coding-blocks/oneauth/commit/1a1e0f83fdb3faa6ded5ac1ed6fa8d307f464e10)

**Comment by firefinchdev** [comment]
Done #268

**Comment by witty123** [comment]
@VibhorCodecianGupta thanks, updated the Issue description
