### ISSUE TITLE
Add contact number in users table

### ISSUE THREAD

**Issue by witty123** [coding-blocks/oneauth#282]
Make it mandatory to fill email and contact number even while logging in through social login.

**Comment by VibhorCodecianGupta** [comment]
@witty123 It's a little unclear.

So right now, the custom strategy requires the username and password for login (no email). Does this issue require an addition of both the email and contact number fields to the login form? I guess that will have to be the case if social login wont be allowed without email and contact either.

**Comment by VibhorCodecianGupta** [comment]
Done, #283 

This adds a mandatory contact number field to signup form, user edit form, admin edit form (where admin can edit user credentials). Please guide whether this is correct or further addition required @witty123

**Comment by Dhroov7** [comment]
@witty123 Please review. #290

**Comment by VibhorCodecianGupta** [comment]
@witty123 great, waiting for the issue! :D

**Comment by wildcod** [comment]
Is it still open for boss 2019?
