### ISSUE TITLE
Api should respond with CORS headers properly

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/oneauth#30]
Since the api endpoint should accept request from other domains, it should reply with proper CORS headers to allow Custom Headers (`Authorization`) and allow request from other origins.

![screen shot 2017-05-15 at 2 27 20 pm](https://cloud.githubusercontent.com/assets/8109774/26050015/b58588f4-397a-11e7-9d0e-4d324e447141.png)

**Comment by abhishek97** [comment]
Fixed in #37

**Comment by rahulyadav170923** [comment]
solved in https://github.com/coding-blocks/oneauth/pull/38
