### ISSUE TITLE
country prefix selector for contact no 

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/oneauth#324]
see here for list of prefixes

https://en.wikipedia.org/wiki/List_of_mobile_telephone_prefixes_by_country 

should be implemented how states and countries were (with seeding script)

**Comment by championswimmer** [comment]
in json

https://gist.github.com/Goles/3196253

**Comment by VibhorCodecianGupta** [comment]
@championswimmer done in 21e4134, committed first.

**Comment by VibhorCodecianGupta** [comment]
@championswimmer done in 895cade, committed first.

**Comment by championswimmer** [comment]
@VibhorCodecianGupta's PR was first. I noted that... 

BUT guys... you need to add it into the form too where the contact no is added 

I think it is important to do it fast, but I think it is a little bit more important to do it correctly and completely, don't you think so ?

**Comment by VibhorCodecianGupta** [comment]
@championswimmer completely done, #326

**Comment by samagragupta** [comment]
@championswimmer It should be closed.
