### ISSUE TITLE
setup unit tests

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/oneauth#332]
- [x] use mocha and chai for tests and assertion
- [x] setup nyc for coverage
- [x] setup travis.yml and .circleci/config.yml for testing on CI
- [ ] travis should upload coverage reports to codecov
- [x] add a simple test - check 1 model or 1 util to make sure the setup works
- [x] tests and test related config should go into `/tests` folder
- [ ] add badges for travis, circleci and codecov to readme

(some of these things might require you to test on a project of your own - setup a sample project in nodejs, setup travis and codecov and make sure your config is ok)

this issue is for setting up the test harness, actual tests for every entitity will be added in other issues.

**Comment by VibhorCodecianGupta** [comment]
@championswimmer #360 completes the issue

**Comment by samagragupta** [comment]
@championswimmer @VibhorCodecianGupta Is it still open

**Comment by YashKumarVerma** [comment]
Issue should be closed now.
