### ISSUE TITLE
implement event subscriptions

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/oneauth#357]
create following files

 - `/src/events/users`
 - `/src/events/demographics` 

they should export functions like

`eventUserCreated(userId)`
`eventUserUpdated(userId)`
`eventDemographicsCreated(demoId, userId)`

these should be async functions so that they can run non blocking. 

the purpose of these functions would be like this - 

```js
function eventUserCreated(userId) {
   // find all EventSubscriptions that exist for {user, created}
   // make a POST request to all the webhookURL for all such clients
}
```

payload of post request should have nominal data like ids 

```
{
  type: "CREATED",
  model: "user",
  success: true,
  id: 1,
  userId: 1   
}
```
<small> in case of user model events, id and userId will be same only</small>

```
{
  type: "UPDATED",
  model: "address",
  success: true,
  id: 10,
  userId: 1

}
```

these functions like `eventUserCreated` should be called from controller for user creation. 

The controller should **NOT** await for event function. The event is fired and forgotten, if the event is not reported, the controller should not get stuck for that.

**Comment by firefinchdev** [comment]
I will working on this

**Comment by VibhorCodecianGupta** [comment]
@championswimmer is this 100% done? In case there's anything left, I can contribute.

**Comment by crownedlake** [comment]
Is this still open?

**Comment by rakshitkumarcse** [comment]
Is this issue still open?

**Comment by championswimmer** [comment]
@Manit1 
Pardon us, actually there was some mixup with the bounties. This issue is worth 2000 and ther UI is worth 2000 separately. 

I am fixing the labels for the same.

**Comment by Manit1** [comment]
@championswimmer No problem! I enjoyed working on the issue 😄 .
