### ISSUE TITLE
Account is Made without Email ID and no Password Length validation

### ISSUE THREAD

**Issue by flaredragon** [coding-blocks/oneauth#40]
This can increase the size of the database by number of non-useful accounts without being validated and the password remains unvalidated and can be the size of one character also which can cause breach of security easily by Brute-Force.
![capture12](https://user-images.githubusercontent.com/29121452/27153311-99804e6c-516e-11e7-8fe1-ba389a35256d.PNG)

**Comment by championswimmer** [comment]
merge into #45
