### ISSUE TITLE
Error handling in oneauth

### ISSUE THREAD

**Issue by witty123** [coding-blocks/oneauth#403]
Don't dump actual errors on user screen. Handle errors gracefully and show "something went wrong". Report error on sentry.

**Comment by championswimmer** [comment]
@VibhorCodecianGupta this also something you can work on. We should have a custom error page. That page should only report the error message, not the full stack trace. 

Should ideally be the last middleware in the server, that catches all failures.

**Comment by VibhorCodecianGupta** [comment]
@championswimmer @witty123 doesn't #289 solve this issue? Apart from displaying a particular error message, that is.

**Comment by championswimmer** [comment]
No it doesn't. It only solves routes not found. It doesn't solve uncaught errors thrown from the middleware stack

**Comment by VibhorCodecianGupta** [comment]
@championswimmer done at #413
