### ISSUE TITLE
'Delete Client' option

### ISSUE THREAD

**Issue by AdityaHirapara** [coding-blocks/oneauth#404]
Currently, User is not able to delete clients.

**Comment by AdityaHirapara** [comment]
We should provide development mode and production mode for clients. In development mode, we can allow deleting, but after enabling production mode client won't be able to delete or revoke it back to development mode. And also in development mode, there should be user limit (maybe 50), so that client can't be used for production in development mode.

**Comment by championswimmer** [comment]
Can you add a flag for development mode ? And then we can look at adding dev mode limits too. Sounds like a good option

**Comment by AdityaHirapara** [comment]
Yeah sure!

**Comment by TdevM** [comment]
Merged and deployed https://github.com/coding-blocks/oneauth/pull/675
