### ISSUE TITLE
[quest] we need "organisations

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/oneauth#428]
So we need organisations.

- [ ] add an orgs model

which should have 
 - org name (like Nagarro)
 - org full name ( like Nagarro Software Pvt. Ltd.)
 - org email domain (something like nagarro.com) (optional)
 - org website 

----

- [ ] many-to-many mapping between orgs and users as OrgAdmins 
so that we can have multiple admins for every org

----

- [ ] another many-to-many mapping between orgs and users called OrgMembers
the org-members table should have three columns

- orgId (ofcourse)
- userId (ofcourse)
- email

**Comment by Dhroov7** [comment]
@championswimmer can I take this issue?

**Comment by VibhorCodecianGupta** [comment]
@championswimmer can i pick this up?

**Comment by championswimmer** [comment]
@VibhorCodecianGupta please go ahead (had a discussion with him previously about this already)

**Comment by VibhorCodecianGupta** [comment]
@championswimmer #431 majority work done, few tweaks coming in
