### ISSUE TITLE
Sign up page accepts whitespace for username, first name and last name fields. 

### ISSUE THREAD

**Issue by AvaniVerma** [coding-blocks/oneauth#45]
To view the problem:
1.Go to https://account.codingblocks.com/signup.
2.Enter tab/space for the above mentioned fields.
3.Enter a valid email ID and password.
4.Press sign up.

We get no error message, however, in ideal conditions, we should get an error for leaving the username, first name and last name fields empty.

**Comment by championswimmer** [comment]
fixed
