### ISSUE TITLE
user referral code generation

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/oneauth#566]
Add a field called "referralCode" to every user 

Referral code should be 6 digit, alphanumeric (alphabets in caps only), first three from username, next three random. For example for me - `ARN8F5` 
This column should be unique (ofcourse)

**existing users**
Run a script to generate referral code for all users and set it to all

** new users**
At signup always generate referral code

Show referral code in `/users/me` page under my profile.

**Comment by championswimmer** [comment]
@TdevM @witty123

**Comment by TdevM** [comment]
[https://github.com/TdevM/oneauth/commit/ae3a16e229bdd140fcb49a4d543aefaee0bc780c](https://github.com/TdevM/oneauth/commit/ae3a16e229bdd140fcb49a4d543aefaee0bc780c)
done!

**Comment by championswimmer** [comment]
@TdevM 

Add a script in script.js to generate a ref code for every user. Existing users do not have a refCode right now.

**Comment by TdevM** [comment]
Added script [https://github.com/coding-blocks/oneauth/pull/575](https://github.com/coding-blocks/oneauth/pull/575)

**Comment by TdevM** [comment]
this should be closed now.
