### ISSUE TITLE
Signup query refcode

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/oneauth#567]
Add a query param `refcode` in signup page. When someone lands via that query param, save it as part of form (use a hidden form field to store it and submit it).

https://account.codingblocks.com/signup?refcode=ARN8F5 

**Further task**
@jatinkatyal13 
Create a redirection strategy in shortlr 
`cb.lk/join/XXXXXX -> https://account.codingblocks.com/signup?refcode=XXXXXX`

**Comment by championswimmer** [comment]
@TdevM @witty123

**Comment by TdevM** [comment]
[https://github.com/TdevM/oneauth/commit/db4cdc68d8e415b7cc2a4304eeff71aab76ebc8b](url)
done!

**Comment by jatinkatyal13** [comment]
@championswimmer Done 🚀
