### ISSUE TITLE
Center align cards

### ISSUE THREAD

**Issue by vdvibhu20** [coding-blocks/oneauth#620]
![Screenshot 2019-06-08 at 3 23 12 PM](https://user-images.githubusercontent.com/18213029/59145450-c1a61c00-8a01-11e9-931e-60582bafa2da.png)
![Screenshot 2019-06-08 at 3 23 44 PM](https://user-images.githubusercontent.com/18213029/59145451-c1a61c00-8a01-11e9-82d8-3e244c940f01.png)

**Comment by imdhruvgupta** [comment]
@vdvibhu20 Please review.
