### ISSUE TITLE
Facebook login button is not working in app

### ISSUE THREAD

**Issue by joeedwin** [coding-blocks/oneauth#634]
**Describe the bug**

Facebook login is not working in app
On pressing FB login button it shows "cannot read property of null"

**To Reproduce**

open app and press Facebook login button

**Expected behavior**

Facebook login should work in mobile app

**Screenshots**

![](https://user-images.githubusercontent.com/26297616/59697115-e9b82b00-920a-11e9-8485-17980502f55e.jpeg)

**Would you like to work on the issue?**
yes

**Comment by nik72619c** [comment]
Is it free to work on ?

**Comment by Sujal123456** [comment]
Can i work on this issue?

**Comment by championswimmer** [comment]
duplicate of https://github.com/coding-blocks/oneauth/issues/980
