### ISSUE TITLE
RUNNING :With SSL (HTTPS) Missing

### ISSUE THREAD

**Issue by XLAR-8** [coding-blocks/oneauth#646]
![1](https://user-images.githubusercontent.com/37559719/60335331-54abf380-99bb-11e9-99d1-31ff4f67c563.png)
RUNNING  oneauth Locally option-2  (For Development) :With SSL (HTTPS)  

content is Missing
wiki is empty.

Filing a bug report: [#14](https://github.com/coding-blocks/oneauth/issues/14)

@championswimmer Please take a look.
Would I get the bounty?

**Comment by XLAR-8** [comment]
@abhishek97 please review!!

**Comment by championswimmer** [comment]
ALready there https://github.com/coding-blocks/oneauth/wiki/Testing-on-Localhost-(with-Social-Logins)#step2-setup-https-proxy-on-localhost
