### ISSUE TITLE
When tried to edit profile to change username it's not editable by user 

### ISSUE THREAD

**Issue by Prateekgaur** [coding-blocks/oneauth#986]
it's like not giving an input form user interface rather it's showing as data fetch from the database
![user account](https://user-images.githubusercontent.com/41009276/82115341-de091780-977f-11ea-9d58-cb7090cd5049.PNG)
![Screenshot (601)](https://user-images.githubusercontent.com/41009276/82115360-ee20f700-977f-11ea-8759-87f9111b58b4.png)

**Comment by championswimmer** [comment]
usernames are not possible to change after creating account. 

#FeatureNotBug
