### ISSUE TITLE
Progress bar doesn't shows realtime percentage values in CB android Application.

### ISSUE THREAD

**Issue by Anish1903** [coding-blocks/oneauth#997]
In Coding Blocks android application, the progress bar doesn't shows real time progress values after watching some videos lectures. It doesn't get updated after watching some video lectures. The progress bar only gets updated when we restart the application or click on "Continue Learning" button.

Screenshots:

Progress bar is at 53%.

![Screenshot_2020-05-18-14-34-15-43_8145aea08c2fe477f98d57a512aa848b](https://user-images.githubusercontent.com/58399776/82197280-6cb09c80-9918-11ea-8fad-c306a3e3b4f6.jpg)

After watching a video lecture and restarting the application.
Progress bar is at is 55%.

![Screenshot_2020-05-18-14-53-54-00](https://user-images.githubusercontent.com/58399776/82197652-df217c80-9918-11ea-8a1b-3ff9f3a09afa.jpg)

**Comment by ArunTeltia** [comment]
This is not the right place to post the issue Try posting the issue at
https://github.com/coding-blocks/CBOnlineApp

**Comment by Anish1903** [comment]
Thanks sir for correcting me.
