### ISSUE TITLE
"My Apps" is hidden in the account page

### ISSUE THREAD

**Issue by HaripriyaB** [coding-blocks/oneauth#998]
### Description
As a user, when I see my account page I find the My Apps option is hidden at the bottom.

### Screenshot
![Screenshot (124)](https://user-images.githubusercontent.com/34762451/82233451-a9e35180-994d-11ea-9e3c-0470670bf41a.png)

### Expected Outcome
Make the option visible

**Would you like to work on the issue?**
- [X] No

**Comment by HaripriyaB** [comment]
@championswimmer bhaiya pls review.

**Comment by roubalsehgal** [comment]
Hi, @HaripriyaB 

I'd already raised an issue for this and to fix this a PR has been done and got merged also.
You can view here 

ISSUE: #1035  PR: #1059
